[build]
  base = "frontend/"
  publish = "frontend/dist/"
  command = "yarn run build"
  environment = { NODE_VERSION = "12", PRESTIGE_BACKEND = "https://b.prestigemad.com/" }

# Following is required for SPAs that handle routing client-side.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
