site_name: "Prestige Docs"

docs_dir: "content"

repo_url: "https://github.com/sharat87/prestige"

theme:
  name: "mkdocs"
  custom_dir: "theme"

# FIXME: Search in docs is not working!
# plugins: []
  # - search:
  #     lang: "en"
  #     prebuild_index: "python"

markdown_extensions:
  - "toc":
      marker: ""
      permalink: true
      toc_depth: "1-5"
  - "attr_list"
  - "admonition"
  # - "codehilite":
  #     linenums: true
  #     guess_lang: false

nav:
  - "index.md"
  - "Guides":
    - "guides/syntax.md"
    - "guides/response-pane.md"
    - "guides/javascript-blocks.md"
    - "guides/templating.md"
    - "guides/cookie-management.md"
  - "tips.md"
  - "about.md"
