site_name: "Prestige Docs"
site_description: "Documentation for the Prestige HTTP client."
site_url: "https://prestigemad.com/docs/"
site_author: "Shrikant Sharat Kandula"

repo_url: "https://github.com/sharat87/prestige"  # TODO: Show a GitHub icon linking to this.

docs_dir: "content"

repo_url: "https://github.com/sharat87/prestige"

theme:
  name: null
  custom_dir: "theme"

markdown_extensions:
  - "markdown_ext"  # Local extension for custom behaviour and features.
  - "toc":
      marker: ""
      permalink: true
      toc_depth: "1-5"
  - "attr_list"
  - "admonition"
  - "smarty"
  # - "codehilite":
  #     linenums: true
  #     guess_lang: false

nav:
  - "index.md"
  - "Guides":
    - "guides/syntax.md"
    - "guides/response-pane.md"
    - "guides/javascript-blocks.md"
    - "guides/templating.md"
    - "guides/cookie-management.md"
    - "guides/proxy.md"
    - "guides/editor.md"
  - "api-reference.md"
  - "tips.md"
  - "about.md"
