name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        # setup-node versions: <https://github.com/actions/setup-node/releases>.
        uses: actions/setup-node@v2.1.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn test
