name: End to end tests

on: workflow_dispatch

jobs:
  all:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: e2e-tests

    steps:
      - uses: actions/checkout@v2

      - name: Get Chrome driver
        run: |
          google-chrome --version

          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
          VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})

          wget -c -nc --retry-connrefused --tries=0 https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_${ARCH}.zip
          unzip -o -q chromedriver_${ARCH}.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          rm chromedriver_${ARCH}.zip

      # We run the script as `bash run.sh` instead of `./run.sh`, because this way we don't require the `run.sh` file to
      # have the executable permission.
      - name: Run tests
        run: |
          bash run.sh
